# -*- coding: utf-8 -*-
"""Dogs_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pE0sqwegxBl0WHGfWuUS7IufVWnOYvX-
"""

dog1 = "Tiger"
dog2 = "Sheru"

print(dog1, dog2)