# -*- coding: utf-8 -*-
"""Dogs_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ItO8u3vw0OPeiSRSBoBiktPr-ANh-s2
"""

items = ["Tiger", 4, "Sheru", 1]
items.insert(1, "Dead")
print(items)